### ISSUE TITLE
Create and deploy react based front-end

### ISSUE THREAD

**Issue by johncokos** [shredfellows/website#1]
Header
Hamburger menu with categories and challenges (not there if you come in directly to an assignment)
4 Quadrants - Video, Readme, Editor, Runner

Components Needed:
Header
Nav (burger menu)
Video
Readme
Challenges (rotator)
Output

Deploy to Heroku.  We will likely move this to AWS in the future ...

**Comment by justeban** [comment]
Deployed Front End to - shredfellows.ccs.net

close #10
